### ISSUE TITLE
New search function: cursor jumps to the left in firefox

### ISSUE THREAD

**Issue by vrs01** [dirkgroenen/mopidy-mopify#105]
Hi!

To start the search function in 1.5.0, I have to type something in the search bar. When the popup opens, the cursor is on the left side of what i just typed. This is only the case in Firefox 38.0.1 on windows 7, in chrome it's fine.

**Comment by aereaux** [comment]
I am having the same problem with Firefox 38.0.1 on Arch Linux.

**Comment by mattb18** [comment]
Same issue here 38.0.1 on OSX.

**Comment by dirkgroenen** [comment]
Can this be related to the [following topic](https://support.mozilla.org/nl/questions/791190)?

**Comment by aereaux** [comment]
I'm not sure what you mean about being related to that topic, but it appears that [here](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/search/search.controller.js#L36) when the focus is set, it sets it at the beginning of the search bar.  Not sure how to fix it, though.

**Comment by dirkgroenen** [comment]
That rule indeed keeps track of the focus boolean, but only provides a var for the [focusMe](https://github.com/dirkgroenen/mopidy-mopify/blob/3397562d8da7e328da05e3654da9ab48f76c758f/src/app/search/menu.tmpl.html#L4) directive to watch. 

Setting the focus on an input field shouldn't be related to moving the mouse. That's why I was wondering if the provided topic in my previous response could have anything to do with it.

**Comment by dirkgroenen** [comment]
Ow wait, now I see what you guys mean. I was thinking about the mouse cursor, but it turns out to be the typing cursor right?

**Comment by aereaux** [comment]
Yes, it is the typing cursor.

**Comment by dirkgroenen** [comment]
Will be fixed in the next release
