### ISSUE TITLE
Does search combine results from different backends?

### ISSUE THREAD

**Issue by eliericha** [dirkgroenen/mopidy-mopify#134]
Hello.

First off kudos for the great interface and functionality, everything works really well overall :)

I have a question regarding search. When I type a search query I can see in the logs that multiple backends are invoked for the search (Spotify, YouTube, Soundcloud), but it seems that the "Tracks" only lists the results of one of the backends.

Is that behavior correct/expected/known problem?

First I only saw Soundcloud results. I thought the problem was that the backend returned too many results, so I limited its number of results. The effect was that now I see only YouTube results. I limited the number of results for that too. Now I still only get YouTube results, but a smaller number of them. So indeed the UI seems to ignore the results of other backends.

Any insight on that?

Sorry if this is a duplicate (I did a quick search of existing issues but didn't find anything about current search behavior)

Cheers!

**Comment by eliericha** [comment]
Ok I just read up about v2.0 a bit, and I guess with the scope intended for the new version (fully support multiple backends), there's no real point in trying to fix this in the current version...

**Comment by dirkgroenen** [comment]
You probably see those multiple requests because Mopidy searches through them all but Mopify only filters Spotify results. 

I indeed want to create a new player, Sonate, which handles results from multiple backends. At the moment there is a branch which already handles those results in search, so if you want to see your other service's results you could manually install that one.
