### ISSUE TITLE
Errors after trying to connect to Spotify (on Chrome).

### ISSUE THREAD

**Issue by klokop** [dirkgroenen/mopidy-mopify#139]
![image](https://cloud.githubusercontent.com/assets/856897/10737780/63423968-7c14-11e5-87bf-662db2208837.png)

Uncaught SyntaxError: Unexpected end of input(anonymous function) @ mopidy-mopify-1.5.7.js:23
(index):1 Uncaught SyntaxError: Unexpected end of input(anonymous function) @ mopidy-mopify-1.5.7.js:23

This only happens on Chrome (45.0.2454.101). Works fine in FireFox.

**Comment by Rambomst** [comment]
I also get this issue.

**Comment by dirkgroenen** [comment]
I'm still running a bit low on time, so let me get on this one as soon as possible!

**Comment by dirkgroenen** [comment]
Could you give me a bit more information:
- When does it show up?
- Does it freeze the app
- Does it stay after a reload?

**Comment by Rambomst** [comment]
I get spammed by this message when pressing the "Reconnect with Spotify" button under services. It doesn't freeze the app and after reload I continue to get spammed and also have the following error.

`mopidy-mopify-1.5.7.js:12746 GET https://api.spotify.com/v1/me 401 (Unauthorized)`

**Comment by dirkgroenen** [comment]
Is this still an issue?

**Comment by kusmierz** [comment]
yes

```
Uncaught SyntaxError: Unexpected end of JSON input(anonymous function) @ mopidy-mopify-1.5.17.js:44678
```

**Comment by akatrevorjay** [comment]
Is there anything we can provide to help debugging this? My spotify actually only connects temporarily when I first connect it, then disconnects and won't pull playlists if I refresh

**Comment by dirkgroenen** [comment]
It could help if you check the network tab and post what the Spotify calls are returning. The calls are made through the bitlabs domain, but filtering on `spotify` will show them.

**Comment by akatrevorjay** [comment]
Yeah, I was doing that to take a look. I'll paste it in a sec, minus tokens.

**Comment by akatrevorjay** [comment]
Figured it out. You *HAVE* to enable third party cookies. In my opinion, this a a bug.

**Comment by kusmierz** [comment]
@akatrevorjay confirmed, I've disabled it too. Dunno if we could classify it as a bug or not, but it should at least warn you...

**Comment by akatrevorjay** [comment]
Can't we just tunnel the requests through the main process anyway? Does the client have to connect directly through bitlabs.nl? I have to look into this more.

**Comment by dirkgroenen** [comment]
Hmm didn't know there are browsers which disable third-party cookies by default. Unfortunately we need to tunnel the stuff through bitlabs in order to get the tokens. Spotify wants us to have a verified callback URL, but since everybody runs Mopidy on their own IP we can't just use that. The tunnel makes sure we always have the same callback url. 

I could try to built some sort of check which tests if the user has third-party cookies enabled...

**Comment by akatrevorjay** [comment]
Sorry Dirk, I wasn't very clear, I meant to tunnel that request to bitlabs
through the mopidy service, that way we can avoid the need for third party
cookies to be enabled.

On Sun, Jun 12, 2016 at 3:57 PM Dirk Groenen <notifications@github.com>
wrote:

> Hmm didn't know there are browsers which disable third-party cookies by
> default. Unfortunately we need to tunnel the stuff through bitlabs in order
> to get the tokens. Spotify wants us to have a verified callback URL, but
> since everybody runs Mopidy on their own IP we can't just use that. The
> tunnel makes sure we always have the same callback url.
>
> I could try to built some sort of check which tests if the user has
> third-party cookies enabled...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dirkgroenen/mopidy-mopify/issues/139#issuecomment-225456955>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABQGIlLxkn76OgXnTrWgpvy1J_kNGFNHks5qLGTHgaJpZM4GV3kp>
> .
>
-- 
Ty,
Trevor

**Comment by dirkgroenen** [comment]
Hmm I'm not sure if that will work. The reason the current implementation works is because of the shared domain we take advantage of. 

The moment you open the client it inserts a frame in the page. The inserted frame shares the same domain as the Spotify callback URL, which makes it able to communicate with that frame and act like we are the same website as Spotify's Callback. So say you would login the following would happen:

1. Press login, Spotify window opens and you fill in your creds. At the same time Mopify starts polling the inserted bitlabs.nl frame for the tokens.
2. Spotify redirects to bitlabs.nl domain where the returned tokens are stored as a cookie
3. Mopify's polling now receives tokens; sets them in it's own storage and uses them for further requests.
