### ISSUE TITLE
Looping one song

### ISSUE THREAD

**Issue by fulaphex** [dirkgroenen/mopidy-mopify#154]
I haven't seen that option and it looks like a basic feature, found in almost every player on the market. Did I miss sth, is it already implemented? Or maybe the protocol that You are using doesn't allow to implement it in a simple way?

**Comment by jodal** [comment]
The Mopidy server supports this by setting both the "single" and "repeat" flags to true, so this is probably a lacking of the Mopidy-Mopify client.

**Comment by dirkgroenen** [comment]
I think Mopify only enables `repeat` at the moment, which should make it repeat your playlist. Though while typing this I remember that that probably doesn't work either since consume mode is enabled...

Let me sort this out the moment I start working on the QueueManager. (#146  is also kinda related to this).
