### ISSUE TITLE
Starting Mopidy-Mopify with systemd service file fails

### ISSUE THREAD

**Issue by getdiniks** [dirkgroenen/mopidy-mopify#156]
Hello,

I am trying to run Mopidy on a RP2. Everything seems to work, only the Mopidy-Mopify webclient doesn't when I start Mopidy as a systemd service.

The problem seems to be that Mopify's sync plugin wants to create a config directory in $HOME/.config/mopidy-mopify but cannot because $HOME doesn't seem to be set when started via systemd.
The Error message is: "Mopify sync extension wasn't able to create a directory."
The offending code is in /usr/local/lib/python2.7/dist-packages/mopidy_mopify/sync.py (It does work when I manually edit sync.py and set userhome = "/etc")

My/etc/systemd/system/mopidy.service file looks like this:
[Unit]
Description=Mopidy  
After=network.target
[Service]
Type=simple
ExecStart=/usr/bin/mopidy --config=/etc/mopidy/mopidy.conf
Restart=on-abort
[Install]
WantedBy=multi-user.target

**Comment by dirkgroenen** [comment]
I've replaced the $HOME var for `expanduser("~")`. Hopefully this should return a correct directory. If not I probably need to look into writing in some `/etc` directory.

**Comment by jodal** [comment]
Since Mopidy 1.1, we have a set of methods that creates and returns the proper dirs for you to store config files, cache data (that can be deleted anytime) and more persistent data (that should not be deleted):

- [Extension.get_config_dir(config)](https://docs.mopidy.com/en/latest/api/ext/#mopidy.ext.Extension.get_config_dir)
- [Extension.get_cache_dir(config)](https://docs.mopidy.com/en/latest/api/ext/#mopidy.ext.Extension.get_cache_dir)
- [Extension.get_data_dir(config)](https://docs.mopidy.com/en/latest/api/ext/#mopidy.ext.Extension.get_data_dir)

These methods will do the right thing both when running as a user and as a system service. Packagers of Mopidy on e.g. Debian and Arch Linux makes sure that they write to directories that the Mopidy process has access to.

Can these methods be of help to you?

**Comment by dirkgroenen** [comment]
Absolutely, great to see the existence of those endpoints. I'll play around with them to solve this issue once and for all.

**Comment by dirkgroenen** [comment]
@jodal could you show an example how/where to use the methods? I've been trying to call `get_config_dir` but I'm not able to get it running without an error.

**Comment by jodal** [comment]
https://github.com/mopidy/mopidy-spotify/blob/38c9088032686fd78d7ae31ad9a262cfada8d510/mopidy_spotify/backend.py#L97

**Comment by jodal** [comment]
You should be able to use `Extension.get_config_dir(config)` without creating an instance of `Extension` first. The code I linked predates `get_config_dir()` becoming a class method.
