### ISSUE TITLE
[V2.0] Queue behavior redesign

### ISSUE THREAD

**Issue by dnr** [dirkgroenen/mopidy-mopify#164]
I tend to listen to whole albums at a time, so I find the dual-queue mechanism quite annoying [1]. I'd like to use the "queue" mechanism exclusively and ignore the "playlist". Currently that means I right-click and "Add to queue" all the time. It would be easier (and much less clicking) if I could just set it so that "Play" meant "Add to queue", and "Play now" was a secondary option buried in the context menu, for when I really do mean that.

[1] I understand that it matches Spotify's behavior, and I find it annoying there too. For an example of what I mean, consider: Nothing is playing. I open up Mopidy and want to play some music. I find an album and want it to start immediately, so I click "Play". It starts playing. Now I look around for what I want to play after that, and find another album. I select "Add to queue". Now my second album plays in the middle of the first album, right after the current track. I can work around this by always using "Add to queue" even when nothing is playing. Though note that if I "Add to queue" then, it takes an extra click to start things playing.

**Comment by dirkgroenen** [comment]
Thanks for your feedback. For what it's worth for me the current queue is holy or whatever and I'm always open for improvements. At the same time I find the queue one of the 'most difficult' parts in a player to build. There are many approaches to go with...

Let me keep this one open and label it as a 2.0. I'm not gonna make any promises that I will change it, but if more people have suggestions or want to think about a solid implementation I would love to hear from them.

**Comment by bigmittens** [comment]
+1 on this.

**Comment by tylerjdurden** [comment]
I know this is an old topic, but I'd like to second (or third) this. I play something then add songs to the queue and they just don't play after because they're in a different playlist? Kind of unintuitive. Also if you finish playing something you can have songs just sitting in the queue. When you click the play button, it starts the Now Playing thing over again rather than just go to the queue.

I imagine most people would want something similar to how Spotify does it (Now Playing and Queue are one thing, one option: add to queue).

I had a modification for my jailbroken iPhone that did queueing perfectly: 3 options. 

* Play Now plays instantly. 

* Play Next plays after this song. 

* Play Last puts it at the end of the queue. 

Very simple but does more than Spotify with nothing confusing or large overhead. I'd argue that this would be a little simpler than the current solution.
