### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by EgidioCaprino** [dirkgroenen/mopidy-mopify#207]
Hi,

I installed mopify on Arch running on a Raspberry PI. I can see it is running because using netstat I see this line

``` bash
tcp        0      0 127.0.0.1:6680          0.0.0.0:*               LISTEN
```

but I cannot access it through the browser:

http://192.168.1.81:6680/mopify/ (connection refused)

Is there anything I need to change in the mopidy configurations?

Thanks

**Comment by kingosticks** [comment]
Change the hostname config value to either 0.0.0.0 or :: as described at https://docs.mopidy.com/en/latest/ext/http/#confval-http/hostname

**Comment by EgidioCaprino** [comment]
Thank you @kingosticks 

I managed to connect. However I can hear no sound. I installed alsa-utils but cannot start alsamixer

``` bash
[alarm@alarmpi ~]$ alsamixer
cannot open mixer: No such file or directory
```

Any idea?

**Comment by kingosticks** [comment]
I don't use Arch Linux but I'd guess something to do with Arch's use of pulseaudio. If you can't find the answer on Google I suggest you try posting at discuss.mopidy.com. These are not issues with mopify.

**Comment by EgidioCaprino** [comment]
So I need pulseaudio, cannot just do it with Alsa, right?

**Comment by dirkgroenen** [comment]
You can use pulsaudio and alsamixer, that's not an issue. Alsamixer not wanting to start (after installing alsa-utils) could suggest you have no sound driver/detected sound card. Check your `aplay -l` output and see if any cards are recognized. 

I'll close this issue since this is, as @kingosticks said, not related to Mopify. I would suggest to do some searching on Google and check the Arch documentation. They've a solid documentation that should you get out of these kind of issues.
