### ISSUE TITLE
Random Playlist after closing and reopening browser window

### ISSUE THREAD

**Issue by PythonSmith** [dirkgroenen/mopidy-mopify#24]
First time I started up mopify my playlists were here, but after reconnecting only this Playlists appear: 
http://prntscr.com/5r31x9

Deleting the mopidy/spotify folder fixes the problem once.

Simliar probems happend in mopidy-spotify
I think it is related to https://github.com/mopidy/mopidy-spotify/issues/27

**Comment by kingosticks** [comment]
That mopidy-spotify bug should have nothing to do with opening and closing
the browser window. It happens when you first start mopidy and it is not
able to load the playlists.

**Comment by dirkgroenen** [comment]
Are you loading the playlists from Mopidy-Spotify or from the Spotify service?

If I remember the playlists you're seeing are from the Spotify user 'null', which gets fetched when the Spotify user ID can't be loaded.

**Comment by PythonSmith** [comment]
Not easy to answer, 
My conf:
http://pastebin.com/V5N1MN3h
Using MPD and Playlist is working nice;
So it seems there is a problem with the Spotify service.

**Comment by dirkgroenen** [comment]
I was referring to Mopify's Spotify service config which has been implemented since version 1.1.0. If you have connected Spotify as a service it will enable Spotify as playlist source by default. This means that playlists are loaded through the Spotify web API instead of Mopidy (better performance when having a lot of playlists on a Raspberry PI). 

On the image below you can see how the page looks like. As you can see I have disabled the Spotify playlist source which means that the playlists I see are loaded from Mopidy. 

![](http://i.imgur.com/d8NYRhV.png)

**Comment by PythonSmith** [comment]
This workaround works :)
But could the reason for the bug be, that I'm logged in with my Facebook account?
I hope my banana pi can handle this

**Comment by dirkgroenen** [comment]
Nope, has nothing to do with how you're logged in on Spotify.

Which Mopify version are you running?

**Comment by PythonSmith** [comment]
Latest git-dev version, everything is git-dev version, (Archlinux on Banana Pro)

**Comment by dirkgroenen** [comment]
Hmm I see this is still a bug. I'll label it and fix it soon.
