### ISSUE TITLE
Ajax artist fails to fetch data

### ISSUE THREAD

**Issue by jaedb** [dirkgroenen/mopidy-mopify#5]
When opening the 'Artist Information' (triggered by clicking on an artist name), the majority of the data fails to load. It fetches the related artists but nothing else.

Tested in Firefox 33, Chrome 38 - both on OSX 10.7.5

In the console view (see screenshot) it doesn't appear the ajax call is fired at all? So wouldn't appear to be a change to the Spotify API, more an issue with the local code.

![mopify](https://cloud.githubusercontent.com/assets/1711444/5059536/955b351c-6d83-11e4-93ca-b1034731be49.jpg)

**Comment by dirkgroenen** [comment]
Just launched the new Mopify which handles this data collecting way better.

I'm quite busy in the coming two weeks, but I'll try to find some time to fully test the client on a Raspberry. I've installed it in the office last week so my colleges are testing it too. 

Closing issue for now since it's related to the old Mopify.

**Comment by kingosticks** [comment]
Awesome speedy week. Looking forward to trying this. Thanks!
