### ISSUE TITLE
Base page links to empty view

### ISSUE THREAD

**Issue by totokaka** [dirkgroenen/mopidy-mopify#54]
When I go to `http://localhost:6680/mopify/` I am redirected to `http://localhost:6680/mopify/#/discover/featured`, which is empty (see photo below). I am also asked to "Connect to the Spotify service first.", even though mopify automatically connects to my Spotify account.

![feurvpp](https://cloud.githubusercontent.com/assets/817001/6319805/19d6540e-bacb-11e4-917b-8ffd04c9af61.png)

**Comment by dirkgroenen** [comment]
I'm indeed still experiencing some problems in the Spotify login procedure. Sometimes when you open the client it won't login until you refresh the client. When this happens the featured playlists page won't be loaded.

At the moment the 'homepage' is statically set to the Featured Playlists page. In the next version I wan't to make this an option so the user can chose a page.

**Comment by totokaka** [comment]
+1 for the ability to choose.

Why is it the Featured Playlists page is empty for me? Maybe it should be changed to the Discover page so it won't be empty?

**Comment by dirkgroenen** [comment]
As I said, your Spotify account hasn't fully connected (at least it looks like it hasn't since your [profile image and name](https://camo.githubusercontent.com/5c13ca2948357b41d16514640d7f7a62fc96d80b/687474703a2f2f692e696d6775722e636f6d2f626f4f33586f382e706e67) haven't been loaded). Featured playlists are only accessibly when a user has been authenticated.

**Comment by totokaka** [comment]
I am not sure whether I am fully loaded or not. My Spotify account is not connected to a Facebook account (as I don't have one), and I have not set an avatar or a name besides the login name. 

If it matters, I am running the `mopidy-spotify` plugin, although I have a feeling it isn't needed.

If I try to reconnect to the Spotify service with the "reconnect with spotify" button on the Spotify Service page, the same blank pop-up as described in #53 shows up.

**Comment by totokaka** [comment]
I suppose it's also worth noting that the "Profile Name" field is completely empty for me, and I cannot change it.

If I disconnect from the spotify service by clicking the arrow icon on spotify in the services page, I can also keep playing music as if I was still connected. This includes changing playlists and searching up artists.

**Comment by dirkgroenen** [comment]
Hmm, that's weird. Could you track down and paste the response of a ```api.spotify.com/v1/me``` request in your developer tools? 

Playlists are loaded once and then controlled from the ```Playlist Manager service```, although you should't be able to get a or remove a song to a playlist or your collection.

Some of the actions go through ```mopidy-spotify``` and some/most of the extra features go through ```Spotify's web API```. That's why you can still perform a search, load your playlists and listen to music. 

Can you give me the URL of the blank popup? This popup is used for the authentication process as described in the [Wiki](https://github.com/dirkgroenen/mopidy-mopify/wiki/Customized-Spotify-Authentication) and should contain ```accounts.spotify.com``` first which redirects to ```mopify.bitlabs.nl```. This normally shouldn't take longer than a few seconds .

**Comment by totokaka** [comment]
Below is the response to the first request to `api.spotify.com/v1/me` on a page load. Sadly, Firefox won't let me copy the raw JSON, so you'll have to do with this image ( :/ )
![h1c512k](https://cloud.githubusercontent.com/assets/817001/6320455/4cfbb672-bade-11e4-92a9-01d3ca9ed15f.png)

The blank popup goes by too fast to really see the URL, but I think it shows `bitlabs.nl` for a split second before it closes, before that it could be that it vists `accounts.spotify.com`. On my phone, I could clearly see a popup going through those two pages.

**Comment by dirkgroenen** [comment]
Your JSON explains why you are not seeing an image and name: your account doesn't contain one. Which means that every thing is going as it should go. Except for the Spotify login popup which opens at every page refresh, but that bug has already been solved in the Development branch.

**Comment by dirkgroenen** [comment]
Fixed in 1.3.1 which I've just released. Note that you should only fill in existing URLs, otherwise you will end up in a redirect loop. I wasn't able to find a way to check if a route exists.
