### ISSUE TITLE
Some comments on the responsive UI

### ISSUE THREAD

**Issue by tlaundal** [dirkgroenen/mopidy-mopify#58]
Great work on the responsive UI, it looks great. However, I have some minor comments. I found it easier to draw on the gui to describe the 'problems':

![f77a0bg](https://cloud.githubusercontent.com/assets/817001/6320389/205d3192-badc-11e4-8597-1e0cb7c60267.png)

I found the icons on the top most annoying, as one was placed on the opposite side of the menu it opens, seemingly to make room for a button which is already present on the screen, but that doesn't have a function when placed there.

PS: I just made a small €10 donation (as anonymous) to support your work. This is really a great project!

**Comment by dirkgroenen** [comment]
The responsive layout has been created within a few hours, just to see how it would work. The problem with the icon in the top left corner has been bothering me since I used it for the first time, so that will definitely be changed. 

To be honest, I'm think about removing, changing or restyling the header in the complete client (desktop as well as mobile) since it doesn't have quite a good function at the moment. 

The player at the bottom of the screen restyles itself when reloading on a lower resolution. What you see is the result after a resize from desktop to mobile size without reloading. I personally don't see this as a 'must fix' at the moment. 

Thanks for your donation and all the issues you're creating! Those really help me to further develop this project.

**Comment by hkultraman** [comment]
hi, sorry for my dump question. How can I access to this UI? I am using my android phone chrome browser access to my mopify. However, it still shows me a desktop edition.

many thx.

**Comment by dirkgroenen** [comment]
@hkultraman please wait for a response in your own issue #90.
