### ISSUE TITLE
src/module.c:3:28: fatal error: libspotify/api.h: No such file or directory

### ISSUE THREAD

**Issue by imjoeco** [dirkgroenen/mopidy-mopify#67]
Attempting to install mopify with 

    sudo pip install Mopidy-Mopify 

terminates with error:

    src/module.c:3:28: fatal error: libspotify/api.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

on every attempt. Working with a fresh installation of mopidy and mopidy-spotify on raspberry pi using raspbian-wheezy.

Currently working around by getting a developer account from spotify, loading libspotify to pi and manually adding api.h file with c-code version of API key but without this, install fails.

**Comment by dirkgroenen** [comment]
Sound more like a [mopidy-spotify](https://github.com/mopidy/mopidy-spotify) problem to me. Maybe @jodal can help you with this?

**Comment by kingosticks** [comment]
You made mopify depend on mopidy-spotify which in turn depends on libspotify, which is not in pip.
> libspotify >= 12, < 13. The official C library from the Spotify developer site. The package is available as libspotify12 from apt.mopidy.com.

**Comment by jodal** [comment]
As Mopidy-Mopify doesn't directly depend on Mopidy-Spotify through code, but is just less useful without the Mopidy install having Spotify support, one solution is simply to drop the Mopidy-Spotify requirement from Mopidy-Mopify.

It shouldn't matter which order you install Mopidy-Spotify and Mopidy-Mopify in. Now, because of the C library dependency of Mopidy-Spotify, you're better off if you install Mopidy-Spotify first (e.g. from apt with `sudo apt install mopidy-spotify` which will also install the C lib) than if you install Mopidy-Mopify first (with `sudo pip install mopidy-mopify`), since pip doesn't support installing non-Python dependencies.

**Comment by dirkgroenen** [comment]
It indeed doesn't depend directly on mopidy-spotify, but the client is quite useful without Spotify at the moment. Till other libraries are supported I would say that listing it as a dependency can't hurt.

**Comment by jodal** [comment]
Well, it does cause harm, ref this bug. Mopidy-Spotify *isn't* automatically installable from pip. You must use a distro package system or read the Mopidy-Spotify docs to get a working install.

**Comment by dirkgroenen** [comment]
Clear, I'll remove it in the next version.

**Comment by dirkgroenen** [comment]
Removed in version 1.3.2.
