### ISSUE TITLE
Timezone for Featured Playlists not localized

### ISSUE THREAD

**Issue by BrettMerrick** [dirkgroenen/mopidy-mopify#69]
Running on a raspberry pi, featured playlists for Friday night appear on a Saturday morning.

$ cat /etc/timezone
Pacific/Auckland
$ date
Sat Feb 28 09:39:05 NZDT 2015
$ date -u
Fri Feb 27 20:40:36 UTC 2015

**Comment by dirkgroenen** [comment]
Have you filled in your county and language code at the settings page?

**Comment by bmernz** [comment]
I have, still the same.

**Comment by dirkgroenen** [comment]
Just noticed in Spotify's docs that it's possible to add a timestamp parameter to the request. I'll add this timestamp parameter in the next version which hopefully solves your problem.

**Comment by dirkgroenen** [comment]
Added a timestamp to Spotify's request. Can you confirm it's working correctly now?

**Comment by bmernz** [comment]
Hi, Just upgraded to 1.4.2, still seem to have the same problem. Do I need to set the timezone in the mopidy config somewhere?

**Comment by dirkgroenen** [comment]
Spotify has an [Web API console](https://developer.spotify.com/web-api/console/get-featured-playlists/?timestamp=2014-10-23T07%3A00%3A00&country=US) where you can create requests. Can you fill in your details and check if Spotify's response is correct?

**Comment by bmernz** [comment]
Hi,

I get the correct response if I provide a localised timestamp - ie. this for Wednesday 29th April, 9:03am:
```
curl -X GET "https://api.spotify.com/v1/browse/featured-playlists?locale=en_NZ&country=NZ&timestamp=2015-04-29T09%3A03%3A00" -H "Accept: application/json" -H "Authorization: Bearer BQBRXLzgvxY--BduqoW5m412zaH2eCGrXWfywhE43V2GV9P3U2zII0xv4GYLA4Am4-ikbRsS5NTAPiK8bGW_4jNg0Teu3MMewembmt8vMBbxnYSup625Hw8DANsnFFHmVNNuWSVf0aZv"
```
produces:
### Request ###
```
GET /v1/browse/featured-playlists?locale=en_NZ&country=NZ&timestamp=2015-04-29T09%3A03%3A00 HTTP/1.1
Host: api.spotify.com
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, compress
Authorization: Bearer BQBRXLzgvxY--BduqoW5m412zaH2eCGrXWfywhE43V2GV9P3U2zII0xv4GYLA4Am4-ikbRsS5NTAPiK8bGW_4jNg0Teu3MMewembmt8vMBbxnYSup625Hw8DANsnFFHmVNNuWSVf0aZv
User-Agent: Spotify API Console v0.1
```
### Response ###
```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000;
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Cache-Control: public, max-age=600
Date: Tue, 28 Apr 2015 21:04:14 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=utf-8
```

```json
{
  "message" : "Happy Wednesday!",
  "playlists" : {
    "href" : "https://api.spotify.com/v1/browse/featured-playlists?country=NZ&locale=en_NZ&timestamp=2015-04-29T09:03:00&offset=0&limit=20",
    "items" : [ {
      "collaborative" : false,
      "external_urls" : {
        "spotify" : "http://open.spotify.com/user/spotify/playlist/2PXdUld4Ueio2pHcB6sM8j"
      },
      "href" : "https://api.spotify.com/v1/users/spotify/playlists/2PXdUld4Ueio2pHcB6sM8j",
      "id" : "2PXdUld4Ueio2pHcB6sM8j",
      "images" : [ {
        "height" : 300,
        "url" : "https://i.scdn.co/image/f6deeeb0c73878356f395686f4b12d95f1e2ef72",
        "width" : 300
      } ],
```
etc.

I note that the response header includes the correct GMT datetime of Tuesday 28 April 9:04pm too.

**Comment by dirkgroenen** [comment]
Hmm, I've no clue why the timestamp in the request ain't working to be honest. I will reopen this and check if again.

**Comment by dirkgroenen** [comment]
Little update, I have been trying to localize the issue but still aren't able to recreate it. I will leave this issue in case I want to dig into it again.

**Comment by oboote** [comment]
Just a little +1 on this :) We're based in GMT+8 so we only get suggested sleep-inducing playlists until mid-afternoon ^^

Site note - ever looked at adding support to browse through the full spotify suggested playlists (as opposed to just the contextual time based ones? "GENRES & MOOD" in particular would bypass the timing issues for us.

Happy to help diagnose (I doubt our CTO will let me open a port to the pi on our local network ^^).

**Comment by oboote** [comment]
(Haven't managed to fix it yet but sharing what I've tried)

Actually I think the problem lies with Spotify ignoring the Z timezone in the timestamp.

Using the API Web-Console
https://developer.spotify.com/web-api/console/get-featured-playlists/#complete

2016-03-08T04:00:00
returns the same results as
2016-03-08T04:00:00Z
but different results from 
2016-03-08T12:00:00

It looks like we therefore need to pass timezone adjusted time (and not standard toISOString() which is in Zulu)

I've tweaked my featured.controller.js using the following logic:

root@musicbox:/usr/local/lib/python2.7/dist-packages/mopidy_mopify/static/debug/src/app/discover/featured# nodejs
>       var date = new Date();
>       var offset = date.getTimezoneOffset() * 60000;
>       var localDate = new Date(Date.now() - offset);
>       var timestamp = localDate.toISOString().slice(0,-5);
> console.log(timestamp);
2016-03-08T12:43:38

(As Spotify doesn't actually read the full ISO string the slice is redundant but trims the string to what is expected)


And... I'd love to say this fixed it... but it hasn't >.< (but it hasn't broken anything either; no change)

Perhaps the Spotify.getFeaturedPlaylists is smarter than I thought and adjusts for timezones? (yet wrongly?)

Back to square one...

According to https://github.com/eddiemoore/angular-spotify (is that what we're using?):
"timestamp - string - Optional. A timestamp in ISO 8601 format: yyyy-MM-ddTHH:mm:ss. Use this parameter to specify the user's local time to get results tailored for that specific date and time in the day. If not provided, the response defaults to the current UTC time. Example: "2014-10-23T09:00:00" for a user whose local time is 9AM."

It looks like we're on the right track - but I'll need to shelve this until tomorrow.

**Comment by dirkgroenen** [comment]
If you want to fiddle around you'll be better of cloning the repo and setting up a dev environment on your pc. You can check the README on how to do it, but in short it's just cloning, installing and running. 

After settings up the environment you can make changes in the `./src` directory and see the changes in your browser. Another plus is that you can submit your changes as a pull request when you've found the bug/issue.
