### ISSUE TITLE
Playlists only load properly on new connection to spotify

### ISSUE THREAD

**Issue by xbow** [dirkgroenen/mopidy-mopify#70]
At first, playlist loading didn't seem to work at all, but I was able to pin it down to the following behavior:
My playlists load properly only if the web client was disconnected from spotify, and the browser was restarted, and a new connection to spotify is established manually. They do not load when I re-open mopify in an existing browser session or when I start a new browser session in which mopify automatically re-connects to spotify because it remembers the settings. So I need to disconnect spotify, restart the browser, and reconnect every time. 

This behavior was observed on two different Windows (7 and 8) PCs with Firefox as well as Chrome. Mopify runs on a Raspberry Pi in the local network. I have around 100 playlists, but they load very quickly when they do. 

I also noticed that when the playlists do not load, the images used by the mopify UI are loaded properly. When the playlists do load, the images only appear AFTER the playlists are fetched. This may be an indication of what is happening... (or not happening)

**Comment by dirkgroenen** [comment]
First; which version are you running and are you loading your tracks from Mopidy or Spotify (switch on Spotify's service settings page)?

**Comment by xbow** [comment]
Version is 1.3.1. Playlists are loading from Spotify. They do work (but take a longer time) when loading from Mopidy. Songs, Albums, and Artists also work as they should (I have only a few albums saved), only playlists do not.

**Comment by dirkgroenen** [comment]
That's weird. Does it generate an error when you're trying to load the playlist?

**Comment by xbow** [comment]
Yes, weird indeed. Since the client performs well when loading playlists from mopidy, which I hadn't noticed before you asked, I can use this workaround, so thank you for that! So the issue is not that urgent any more, but it is still strange... so to answer your question:

When I load the client in the browser it automatically loads /mopify/#/discover/featured. This page gives a "Please connect with the spotify service first" whenever I refresh it, even if spotify is listed as "connected" under services. Strange enough, /discover/featured does load a number of playlists to check out (which it doesn't when I'm really disconnected).

When I click on playlists, the page loads instantly, but empty, and without an error. Songs, Albums and Artists are displayed correctly without an error.

I also didn't notice anything unusual in the mopidy logfile (mopidy runs as a service on a headless raspberry), but if I understand correctly, mopify doesn't go through mopidy in this case anyway? All I can see here is that .js, .css and images are loaded from the http server everytime I reload the client.

**Comment by xbow** [comment]
I just noticed: Sometimes there is a delay before the spotify service registers as "connected". Could it be the error message is given before waiting for the spotify connection and then the client gives up on loading the playlists right away?

**Comment by dirkgroenen** [comment]
The homepage doesn't always load correctly indeed, since connecting to the Spotify API takes a bit longer sometimes. When this happens you will see the message 'please connect to Spotify', but most of the time it will show the playlists a few seconds later, or when navigating from and to the page. 

When you open a playlist or album it will usually open the ```/mopify/#/music/tracklist/{uri}``` page. The ```uri``` gets parsed to Mopidy which will return the tracks. An empty page can mean two things:
- Mopidy wasn't able to find any tracks for the provided URI (Spotify isn't correctly connected to Mopidy? Note: I'm not referring to Mopify's Spotify Service, I'm referring to the mopify-spotify extension.)
- The URI wasn't correct, although this almost can't happen.

Are you sure that mopify-spotify is working as it should be? What does mopidy output in the console when starting it using the command ```mopidy```? Normally you should see something like ```Loaded x spotify playlists``` after a moment. This indicates that at least playlists are loaded correctly into Mopidy.

**Comment by xbow** [comment]
Yes, mopidy works as it should when started from the console, it shows 110 playlists load. I also have no problems browsing and listening with the musicbox_webclient or MPD clients. 

The /music/tracklist pages also work as they should. It is only /music/playlists that comes up empty. 

/music/playlists also doesn't show any indications of a loading process. All other pages display a bar and rotating circle to indicate something is loading, the empty playlist list shows up without delay.

MAybe this will help: I used the firefox network monitor to check on mopify. I see GET requests to the spotify API, and the following responses:

    https://api.spotify.com/v1/users/sebx42/playlists?limit=50

which returns a 304 no modified code. I can also browse the json response which contains an array of 50 playlists. There is a second get request for 50 more playlists:

    https://api.spotify.com/v1/users/sebx42/playlists?offset=50&limit=50

which returns a 304 as well and 50 more playlists. But there is no third request for playlists. The response also contains "total: 109" and "next: https://api.spotify.com/v1/users/sebx42/playlists?offset=100&limit=50", but no further request is sent by mopify.

So maybe the process isn't finished because I have too many playlists? Is there a way for me to change the limit and offset settings to a larger value to test?

--

Next, it gets weird. I tried to see what happens when I disconnect mopify from spotify, restart the browser, load mopify, and then re-connect the service. As I wrote above, this loads my playlists succesfully.

BUT there is NO GET request to the spotify api, so I don't understand where the playlists come from, probably from some kind of local cache that results from an earlier attempt to get the playlists from mopidy?

If this is the case, it supports the hypothesis that getting the playlists from spotify may not work at all.

**Comment by dirkgroenen** [comment]
It's weird that your third call isn't made, since the returned results contain a ```next``` link. I must say, I can't think of something which could cause this problem at the moment...

When you disconnect Spotify (or disable the option that loads playlists from Spotify) Mopify will load the playlists from Mopidy. That's why you see your playlists when you've disconnected the Spotify service. 

At the moment you could disable the option on Spotify's settings page as a workaround so you can still access your playlists. 

![http://i.imgur.com/SggLwYD.png](http://i.imgur.com/SggLwYD.png)

**Comment by xbow** [comment]
Ok, I will use the workaround for now. Thank you for all your time!

Just to be sure, I unsubscribed from some playlists and indeed, they load correctly when under 100 and fetched in 2 calls.

**Comment by dirkgroenen** [comment]
Ah good to know, that gives me a direction to look at! I'll let you know when I've found the problem and fixed it.

**Comment by srodrig0209** [comment]
I'm seeing this as well, but I actually do get an error in the console. The right hand window is a fresh incognito window.

![screen shot 2015-03-25 at 12 24 29 pm](https://cloud.githubusercontent.com/assets/2318521/6829461/08e37320-d2ea-11e4-95d2-58d87b54cae4.png)

**Comment by dirkgroenen** [comment]
This is fixed in the next release (1.4.0)
