### ISSUE TITLE
Queue logic inconsistent with official spotify client

### ISSUE THREAD

**Issue by totokaka** [dirkgroenen/mopidy-mopify#73]
I just saw issue #49, and it got me thinking about how the queue should work.

In the official spotify client, it's like this, from what I remember:
  - When you start playing from an album, playlist or anywhere, all the songs in that 'list' is added to the queue, but with a low priority
  - When you add a song, album or playlist to queue that song or 'list' is added to the queue, but with high priority, before all songs with low priority and after all other songs with high priority

In practise this makes the play next button much more useless, as most often you could just add that song to queue, and it will be played next, after all the other songs you want to play 'now' has been played.

The advantage of the system described here, that spotify uses, over the system currently implemented, is that you can go through songs from different playlists, albums and artists and add them to the queue in the way you want to listen to them, even though you are already listening to an album. I use this feature all the time on my phone.

**Comment by dirkgroenen** [comment]
Correct, but there is one problem I've mentioned before: Mopify can't control the queue and playback controller like that. In Mopidy I have only two options: 
- Shuffle, which plays the queue at random order (doesn't shuffle the queue) 
- Normal, which plays the queue from top to bottom.

Duo this it isn't possible to add a higher or lower priority track to the queue. The only workaround would be to disable shuffle and start playing from top. Reordering the tracklist (queue) is possible, so that could be connected to the shuffle button. But I'm already expecting many problems with that, since that would require many API calls to move tracks around the queue. 

That's why I had added 'Play next' (which should be a Mopidy API feature), but that didn't work. An other solution could be to add a 'Play next', which adds the track after the current playing track and disabled the shuffle mode. But there is no way of controlling this, since other users could be enabling shuffle mode again. 

So, to wrap it all up; this isn't as easy to realize without rewriting Mopidy's playback/tracklist controller.

**Comment by kingosticks** [comment]
I think you might be confusing Mopidy's shuffle and random features:
* Shuffle, which shuffles the tracklist 
* Random, which plays the tracklist in a random order (doesn't shuffle the tracklist).

Mopidy allows you add tracks to the queue at an arbitrary offset. I think you'd just need to remember which track is the first 'low priority' one and just add stuff above that. Shuffle can take start and end arguments so if you wanted you could just shuffle the high priority stuff, or shuffle each priority separately.

**Comment by dirkgroenen** [comment]
Ah I didn't know that. In that case it should definitely be possible to achieve this by replacing the current Shuffle action so it replaces the tracklist in random order and let the 'Play next' button add it at the top of the queue. 

Remembering the first low priority track could be dangerous when using the client at the office (for example), since you don't know what the other users are doing.

**Comment by kingosticks** [comment]
There is scope for extending Mopidy to support track priority as it's currently missing from the MPD support.

**Comment by dirkgroenen** [comment]
You're referring to [this method](https://docs.mopidy.com/en/latest/_modules/mopidy/mpd/protocol/current_playlist/#prio)?

**Comment by totokaka** [comment]
Here is my take on this:

When shuffling/playing in random order, the queue should be replaced with the same tracklist but in random order.
When playing a tracklist normally, add it as the current queue(replace).
When adding to queue, add the track/tracklist that should be queued to the currently playing tracklist/queue with an offset equal to the lenght of a list containing all tracks added to queue, and add the track/tracklist to be queued to the local list of queued tracks. This local list can also just be a number of how many songs are queued.
 I guess this would all have to be done on the server side.

**Comment by kingosticks** [comment]
Yes, that method.

**Comment by dirkgroenen** [comment]
Might some good news for @totokaka. I have been playing around with this lately and integrated it in version 1.5.0 which I released tonight. 

It's quite a hack, so you should only use Mopify as a client to prevent weird things from happening. For more information please check the [Wiki](https://github.com/dirkgroenen/mopidy-mopify/wiki/Queuemanager) where I've written a bit about how it works.
