### ISSUE TITLE
No way to know which playlist is currently being played.

### ISSUE THREAD

**Issue by DecayConstant** [dirkgroenen/mopidy-mopify#74]
I work in an office which uses Mopify to manage the music we play publicly.  Everyone who works here has access to the server and we have a lot of playlists that have been added.  The problem is that there is no way to know which playlist is currently being played.

There's no indicator in the Playlist section.  I can tell which song is being played, and I can click on the little playlist button next to the currently playing song, but the page I get taken to does not have the name of the Playlist anywhere on it.  The title of the page only says "CURRENT TRACKLIST."   Right now no playlist pages display the name of the playlist they are displaying.

So!  Maybe there is a way to tell and I've totally missed it.  If that is the case please let me know.  Otherwise, this is a feature request for that ability.  I think all you need to do is display the name of the playlist on all playlist pages.

**Comment by dirkgroenen** [comment]
It isn't possible to track the current playing playlist on a solid reliable way. The very first version of Mopify (a year ago) contained this 'playlist tracker', which actually works well when using mopidy from one client, but this didn't worked good enough since there isn't an official way from Mopidy to get the current playing playlist.

A possible solution would be to compare the current tracklist with all you playlists, but I'm not going to implement that since that will ask too much from the client. Especially when you have many playlists.

**Comment by dirkgroenen** [comment]
With the release of 1.5.0 a new Queue Manager has been created. This will make it possible to send the current playing playlist/album/artist to each client.

I will add milestone to this idea, but mostly as a 'nice to have' instead of prio.
