### ISSUE TITLE
Removing songs fails while playing radio

### ISSUE THREAD

**Issue by timdp** [dirkgroenen/mopidy-mopify#89]
If I follow these steps:

1. Start artist radio.
2. Browse to an album.
3. Right-click a song and add it to the tracklist.
4. Go to the tracklist.
5. Right-click the same song and remove it.
6. Reload the page.

After step 5, the song disappears as expected. However, after reloading, it just re-appears. It seemed to work while playing an album, so I guess it's got something to do with the way artist radio works internally?

**Comment by dirkgroenen** [comment]
It's weird that the songs are re-appearing. The radio feature adds songs in batches, but doesn't check the tracklist so it should not have anything to do with this. 

I'll check it out and try to simulate this.

**Comment by dirkgroenen** [comment]
I've checked the code and try to simulate the issue but it just doesn't happen to me. Looking to the code it shouldn't be possible since the deleted track is sent to Mopidy which deletes the track from the tracklist by it's unique URI. 

Can you check if it happens every time and if it also happens when not using the radio function?

**Comment by dirkgroenen** [comment]
Should we fixed in 1.5.0
